### ISSUE TITLE
`ruamel.yaml` dependency conflict

### ISSUE THREAD

**Issue by burnout87** [oda-hub/nb2workflow#137]
When building the container from the following repository : https://gitlab.renkulab.io/astronomy/mmoda/ibis-isgri-spectrum , when enabling the installation of the `renku-graph-vis` plugin.

The error disappears by removing the `cwl` requirement for `nb2workflow` .

Any ideas?

the error I encounter the following:

```bash
90.68 ERROR: Cannot install nb2workflow and renku because these package versions have conflicting dependencies.
90.68 
90.68 The conflict is caused by:
90.68     cwltool 3.1.20230425144158 depends on ruamel.yaml<0.17.22 and >=0.15
90.68     cwlgen 0.2.8 depends on ruamel.yaml==0.13.13
90.68     cwltool 3.1.20230425144158 depends on ruamel.yaml<0.17.22 and >=0.15
90.68     cwlgen 0.2.7 depends on ruamel.yaml==0.13.13
90.68     cwltool 3.1.20230425144158 depends on ruamel.yaml<0.17.22 and >=0.15
90.68     cwlgen 0.2.6 depends on ruamel.yaml==0.13.13
90.68     cwltool 3.1.20230425144158 depends on ruamel.yaml<0.17.22 and >=0.15
90.68     cwlgen 0.2.3 depends on ruamel.yaml==0.13.13
90.68     cwltool 3.1.20230425144158 depends on ruamel.yaml<0.17.22 and >=0.15
90.68     cwlgen 0.2.2 depends on ruamel.yaml==0.13.13
90.68     cwltool 3.1.20230425144158 depends on ruamel.yaml<0.17.22 and >=0.15
90.68     cwlgen 0.2.1 depends on ruamel.yaml==0.13.13
90.68     cwltool 3.1.20230425144158 depends on ruamel.yaml<0.17.22 and >=0.15
90.68     cwlgen 0.2.0 depends on ruamel.yaml==0.13.13
90.68     cwltool 3.1.20230425144158 depends on ruamel.yaml<0.17.22 and >=0.15
90.68     cwlgen 0.1.0 depends on ruamel.yaml==0.13.13
90.68 
```

**Comment by volodymyrss** [comment]
cwl is an [optional requirement](https://github.com/oda-hub/nb2workflow/blob/b686dae63c9865374e4a6496f20050961f26be07/setup.py#L48-L50) so you should be able to install without it. 

cwl is needed in some cases, but it's not always possible to reconcile dependencies, depending on your base environment.

**Comment by burnout87** [comment]
It works indeed by removing the `cwl` requirement.

Is it ok withouth that ? @ferrigno

**Comment by ferrigno** [comment]
I do not know. I copied the requirement on nbworkflow from the oda-hub guide to make an MMODA service. This is a question for @dsavchenko or @volodymyrss

**Comment by volodymyrss** [comment]
> I do not know. I copied the requirement on nbworkflow from the oda-hub guide to make an MMODA service. This is a question for @dsavchenko or @volodymyrss

Not every python package can be installed in every environment. Your environment was incompatible with this package will full set of options.
In this case, as it is in general the case with python packages, reconciliation can be achieved by reducing options or changing versions.

But, in this case, the title issue speaks about `renku-graph-vis` and you are now talking about requirement on `nbworkflow`.
Which is it?

**Comment by ferrigno** [comment]
To make an MMODA service, I need to have nb2workflow with certain optional additions in my requirements, according to the guide.  In the same guide, it is mentioned that I can use renku-graph-vis to visualize ontology terms.  So I added this to the requirements and run into the conflict described above.  This is why I reported this issue. I hope this clarifies the context and explains my reasons.

**Comment by volodymyrss** [comment]
Thanks for the details!

> To make an MMODA service, I need to have nb2workflow with certain optional additions in my requirements, according to the guide. 

Could you please point to which instruction in the guide suggests these extra options?

Last time there was a reference to cwl in the guide was 6 month ago before it was [commented](https://github.com/oda-hub/hugo-odahub/commit/41e0c5d846aa53a84e12c0e05c43bff9830d232b). But even then it was optional and not applicable to renkulab.

> In the same guide, it is mentioned that I can use renku-graph-vis to visualize ontology terms. So I added this to the requirements and run into the conflict described above. This is why I reported this issue. I hope this clarifies the context and explains my reasons.

Could you please check with the guide as it is now? Might have been some misunderstanding.

**Comment by burnout87** [comment]
https://github.com/oda-hub/hugo-odahub/pull/87 fixed the doc with updated screenshots
