### ISSUE TITLE
check size of the file before download

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/nb2workflow#156]
if possible to check, dont download above limit.

if not possible, when downloading in chunks, stop at some point.

**Comment by burnout87** [comment]
I was thinking of introducing a configuration file, using the same approach the dispatcher-app has, what do you think?

It will help in the long term for several other parameters

**Comment by volodymyrss** [comment]
Maybe, but rather with dynaconf like in oda-bot.
nb2workflow is meant to be used also in command line, so the options should be easy to override from command line, without code duplication.
