### ISSUE TITLE
Please revert back my unwanted push

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/nb2workflow#188]
My apologies: I merged the local master and pushed it by error by clicking on the wrong place in VSCODE.

My commit is 8893c2e710c8e7f8c236d023dbdb26937b73cfbb 

The last commit by Denys is 4af332b2c46411db2d3a23ac72dd41bd50d468c0

**Comment by volodymyrss** [comment]
See #189 . Also just to prevent possible issues like that, I remove the rights to do this.
