### ISSUE TITLE
boolean parameters can't be set to false

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/nb2workflow#21]
I demonstrate the issue here https://github.com/dsavchenko/nb2workflow/commit/afecab20a0a29f9dcd79bbc9aee41c7cc729d5f2

The only way to set the parameter to False is the empty GET parameter value. False or false are interpreted as True

**Comment by volodymyrss** [comment]
yeah I used integer for this. Did not make any effort to do this right. Feel free to try! Else I do in a week.
