### ISSUE TITLE
make cell-by-cell progress messages

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/nb2workflow#25]

**Comment by volodymyrss** [comment]
@okolo is it right that you want to help with this?

I copy the relevant reference here. This is where the message is sent https://github.com/oda-hub/nb2workflow/blob/a9ba65cfb9724423f7b4a2da6230f8bc48f2efd2/nb2workflow/service.py#L223

It would need to be so that in [this](https://github.com/oda-hub/nb2workflow/blob/a9ba65cfb9724423f7b4a2da6230f8bc48f2efd2/nb2workflow/service.py#L178) call there is some iteration and with every cell another `perform_callback` is sent with `action=progress` and `message=your-custom-message-here`.

Actually I do not remember if these are the exact keywords at this moment, @burnout87 looked into this more recently, could you please advise?

**Comment by okolo** [comment]
> @okolo is it right that you want to help with this?
> 
> I copy the relevant reference here. This is where the message is sent
> 
> https://github.com/oda-hub/nb2workflow/blob/a9ba65cfb9724423f7b4a2da6230f8bc48f2efd2/nb2workflow/service.py#L223
> 
> It would need to be so that in [this](https://github.com/oda-hub/nb2workflow/blob/a9ba65cfb9724423f7b4a2da6230f8bc48f2efd2/nb2workflow/service.py#L178) call there is some iteration and with every cell another `perform_callback` is sent with `action=progress` and `message=your-custom-message-here`.
> 
> Actually I do not remember if these are the exact keywords at this moment, @burnout87 looked into this more recently, could you please advise?

@volodymyrss yes, I will try to help. I am inspecting the code right now.

**Comment by burnout87** [comment]
> It would need to be so that in [this](https://github.com/oda-hub/nb2workflow/blob/a9ba65cfb9724423f7b4a2da6230f8bc48f2efd2/nb2workflow/service.py#L178) call there is some iteration and with every cell another `perform_callback` is sent with `action=progress` and `message=your-custom-message-here`.
> 
> Actually I do not remember if these are the exact keywords at this moment, @burnout87 looked into this more recently, could you please advise?

The keywords the dispatcher accept within the context of `callback`(s) are:

https://github.com/oda-hub/dispatcher-app/blob/898cca6483ffab2acf36b7fe20dfa752324b0924/cdci_data_analysis/analysis/job_manager.py#L96-L99

**Comment by volodymyrss** [comment]
> > @okolo is it right that you want to help with this?
> > I copy the relevant reference here. This is where the message is sent
> > https://github.com/oda-hub/nb2workflow/blob/a9ba65cfb9724423f7b4a2da6230f8bc48f2efd2/nb2workflow/service.py#L223
> > 
> > It would need to be so that in [this](https://github.com/oda-hub/nb2workflow/blob/a9ba65cfb9724423f7b4a2da6230f8bc48f2efd2/nb2workflow/service.py#L178) call there is some iteration and with every cell another `perform_callback` is sent with `action=progress` and `message=your-custom-message-here`.
> > Actually I do not remember if these are the exact keywords at this moment, @burnout87 looked into this more recently, could you please advise?
> 
> @volodymyrss yes, I will try to help. I am inspecting the code right now.

Great!
Please ask here if you have any questions!

**Comment by volodymyrss** [comment]
> > It would need to be so that in [this](https://github.com/oda-hub/nb2workflow/blob/a9ba65cfb9724423f7b4a2da6230f8bc48f2efd2/nb2workflow/service.py#L178) call there is some iteration and with every cell another `perform_callback` is sent with `action=progress` and `message=your-custom-message-here`.
> > Actually I do not remember if these are the exact keywords at this moment, @burnout87 looked into this more recently, could you please advise?
> 
> The keywords the dispatcher accept within the context of `callback`(s) are:
> 
> https://github.com/oda-hub/dispatcher-app/blob/898cca6483ffab2acf36b7fe20dfa752324b0924/cdci_data_analysis/analysis/job_manager.py#L96-L99
> 
> `'done', 'failed', 'progress', 'submitted', 'ready', 'unknown', 'unaccessible','aliased', 'post-processing'`
> 
> As of now, the message/email will be sent in case of `done` and `failed`

Thanks! There were two aspects to make sure:
* request parameter to pass state change. it's `action` but it's configurable. could please confirm with code reference @burnout87 ?
* request parameter which gives more comment on the state, its shown in the frontend and API. `message`, right? @burnout87

**Comment by burnout87** [comment]
> 
>     * request parameter to pass state change. it's `action` but it's configurable. could please confirm with code reference @burnout87 ?

It is configurable, but at the moment not within the call_back function. 

When creating a `Job` object:
https://github.com/oda-hub/dispatcher-app/blob/898cca6483ffab2acf36b7fe20dfa752324b0924/cdci_data_analysis/analysis/job_manager.py#L55-L69

and during the callback the job is created here:

https://github.com/oda-hub/dispatcher-app/blob/898cca6483ffab2acf36b7fe20dfa752324b0924/cdci_data_analysis/flask_app/dispatcher_query.py#L1051-L1060

the status is extracted here:

https://github.com/oda-hub/dispatcher-app/blob/898cca6483ffab2acf36b7fe20dfa752324b0924/cdci_data_analysis/flask_app/dispatcher_query.py#L1065-L1068

In any case, to have a configurable status keyword, it is an easy code adaption 

> 
>     * request parameter which gives more comment on the state, its shown in the frontend and API. `message`, right? @burnout87

it is part of the response of the `run_analysis` endpoint, if that is what you mean
