### ISSUE TITLE
Probably makes sense to use CustomJSONEncoder from oda_api (after it being moved there from dispatcher)

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/nb2workflow#42]

**Comment by volodymyrss** [comment]
would be best to avoid making a dependency on oda_api here. I will try, or maybe we can extract it.

**Comment by dsavchenko** [comment]
It could be optional dependency

**Comment by volodymyrss** [comment]
but you propose to use it for encoding all responses, or not? If yes it's non-optional

**Comment by volodymyrss** [comment]
Yeah but ODA is half of the uses as of now. Need to annotate different output types too then.

**Comment by volodymyrss** [comment]
Could you implement it, I guess it's not too long?

**Comment by dsavchenko** [comment]
Somehow related question I left in a comment in oda_api code https://github.com/oda-hub/oda_api/blob/b5d74152edaa49b292cea8752fa814d0c2f1ccda/oda_api/json.py#L31
when doing refactoring PR

**Comment by volodymyrss** [comment]
> One question. Why not super() here?
> 
> https://github.com/oda-hub/nb2workflow/blob/1de36370b9ca2e065eacac2938c7b3392bec3dd5/nb2workflow/service.py#L75

It's somewhat old code that migrated. Super should work, you can add it if you want.
