### ISSUE TITLE
Backward-incompatible changes in owl_type

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/nb2workflow#48]
1. understand_comment_references("oda:upper_limit 1") = {'owl_type': None, 'extra_ttl': None}
2. `owl_type` of output products are now oda:UUID instead of referencing type directly, which is not backward compatible with current plug-in
3. understand_comment_references("oda:limits 1, 2") owl_type is not related either to oda:WorkflowParameter or any xsd type. 
4. Related general question. Are we going to create e.g. oda:Integer class and relate it somehow to xsd:int ?

**Comment by volodymyrss** [comment]
I am going to change the title since I am not sure which is the bug. I understand that there are outputs which do not work for you, I add them into tests. If there are other cases you rely upon, quote them so we can add them to tests too.

**Comment by volodymyrss** [comment]
> The first point in the list is definitely a bug

in fact, I think rather not. How do you expect to interpret a line without a base type? In fact, this function alone can not do it. We'd need to have it also use the default value type, as it's done without a comment.

Before, the comment was only used when an extra type annotation is provided. Now you want it to automatically work when there is no type in the comment?

This works instead:

`understand_comment_references("xsd:int; oda:upper_limit 1") == "http://odahub.io/ontology#1integer_Integer_upper_limit`

Combining both methods of deriving type, from comment and value, is a useful feature, but it's not something we quite had before.

**Comment by dsavchenko** [comment]
But 
```
understand_comment_references("oda:limits 1, 2")['owl_type'] = 'http://odahub.io/ontology#1integer_2integer_lower_limit_upper_limit'
```
which doesn't derive known type (my 3rd point) but at least it's not None, and it generates some ttl with limits

**Comment by dsavchenko** [comment]
After all, why do we want to deviate from previous behavior of deriving argument type from value for xsd types if only additional information (limits) is added to it?

**Comment by volodymyrss** [comment]
> But
> 
> ```
> understand_comment_references("oda:limits 1, 2")['owl_type'] = 'http://odahub.io/ontology#1integer_2integer_lower_limit_upper_limit'
> ```
> 
> which doesn't derive known type (my 3rd point) but at least it's not None, and it generates some ttl with limits

your third point is also in the situation which should not be used in fact. It's circumstantial that it works, it should be changed actually.

**Comment by volodymyrss** [comment]
> After all, why do we want to deviate from previous behavior of deriving argument type from value for xsd types if only additional information (limits) is added to it?

previous behavior is that if there is no comment, default type is used. Is this behavior broken?

Combining default type with annotation is new behavior.

There is one case where the answer is straightforward - when there is no type in the comment, only predicates. This can be added.

**Comment by dsavchenko** [comment]
If there is a type in comment and the default value doesn't match it, I think, this should be checked on validation

**Comment by volodymyrss** [comment]
> If there is a type in comment and the default value doesn't match it, I think, this should be checked on validation

Yes, that's what I meant by "reconciling" but it's not completely straightforward, there are some corner cases. E.g. if the default value is int but annotated as float - we should want to cast it (many cases like this for possible casting), else it's this typical a bit annoying behavior of putting extra '.' to be sure. Even without casting, the types can be subtypes of each other, leading to different desired behaviors. Or, if they are completely unrelated, in which case we might want to make a combined type.

I'll just add a simple case if I manage soon, but I an not fully get around to it until later today probably.

**Comment by volodymyrss** [comment]
I am not sure this is all that is needed, but see #49 
The change in the output behavior was actually a regression.
But I also added further treatment of default type and slightly refactored.

> Related general question. Are we going to create e.g. oda:Integer class and relate it somehow to xsd:int ?
Can we just use xsd:int when feasible?
