### ISSUE TITLE
Adding tags to be extracted for specific astrophysical source.

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/nb2workflow#54]
# Advances Domain

* community-expanding feature

In this workflow 
https://gitlab.astro.unige.ch/hmxb/hmxb-nustar/-/blob/master/ep_cf_2023-02-07.ipynb
which should be applied to several astrophysical sources, I have a cell tagged as "refs" which contains information on the astrophysical source such as the literature references url, some relevant properties derived from them.

Would it make sense to add to nbadapter the possibility to extract this information from the notebook regarding the specific astrophysical object and observation that is analyzed? 

The code adaptation is easy and I have made it already locally, but it is unclear if this fits in the general scope of the module or if it is too specific.

**Comment by volodymyrss** [comment]
More generally, extra annotations can be added to the graph with ttl annotations

like it's done [here](https://github.com/oda-hub/nb2workflow/blob/master/tests/test_semantic_comment.py#L52) for the version.

We can add extra parsing of references at some other level, here we just add annotation by adding lines like this in `parameters` cell:

```
# oda:reference https://doi...
# oda:relevantForObject oda:Crab
```

we'll need to be a bit more clear on the reference and relevance predicates

**Comment by volodymyrss** [comment]
you can add these annotations right now and they will be parsed and reported. 
To understand how to proceed further, we need to know how do you want to use them.

**Comment by volodymyrss** [comment]
I added a test showing how to use these extra annotations, I add help too

https://github.com/oda-hub/nb2workflow/blob/8cc156e6d177205f6be9a15cf58a80f841a32061/tests/test_semantic_comment.py#L64-L68
