### ISSUE TITLE
make sure nb2rdf returns outputs and default values

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/nb2workflow#69]

**Comment by burnout87** [comment]
Could it be related to the fact that within the function `function_semantic_signature` the argument `output`(those extracted from the notebook) are not actually used?

https://github.com/oda-hub/nb2workflow/blob/30e354f5aa3a803f79ee3fcacb290fc53e6386d1/nb2workflow/ontology.py#L65-L95
