### ISSUE TITLE
make nb2service work without rdf extra

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/nb2workflow#88]
following https://github.com/oda-hub/nb2workflow/issues/87

**Comment by dsavchenko** [comment]
Looks like it's not so easy, rdflib is currently widely used throughout the code. We can probably add it to the direct requirements of service extra.

**Comment by volodymyrss** [comment]
could you add it where needed?

**Comment by dsavchenko** [comment]
Actually, as it is used in nbadapter, I propose to add it globally
